[
  "#include <Wire.h>",
  "#include <LiquidCrystal_I2C.h>",
  "",
  "// Initialize I2C_LCD with address 0x27 (commonly used address)",
  "LiquidCrystal_I2C lcd(0x27, 16, 2);",
  "",
  "// Define ultrasonic sensor pins",
  "#define TRIG_PIN 2",
  "#define ECHO_PIN 3",
  "",
  "void setup() {",
  "  // Initialize serial communication for debugging",
  "  Serial.begin(9600);",
  "",
  "  // Initialize I2C_LCD",
  "  lcd.begin();",
  "  lcd.backlight();",
  "  lcd.setCursor(0, 0);",
  "  lcd.print(\"Parking Assist\");",
  "",
  "  // Set up ultrasonic sensor pins",
  "  pinMode(TRIG_PIN, OUTPUT);",
  "  pinMode(ECHO_PIN, INPUT);",
  "}",
  "",
  "void loop() {",
  "  // Measure distance",
  "  long duration, cm;",
  "  ",
  "  // Clear the TRIG pin",
  "  digitalWrite(TRIG_PIN, LOW);",
  "  delayMicroseconds(2);",
  "  ",
  "  // Set the TRIG pin HIGH for 10 microseconds",
  "  digitalWrite(TRIG_PIN, HIGH);",
  "  delayMicroseconds(10);",
  "  digitalWrite(TRIG_PIN, LOW);",
  "  ",
  "  // Read the ECHO pin, and calculate the distance",
  "  duration = pulseIn(ECHO_PIN, HIGH);",
  "  cm = duration * 0.034 / 2; // Convert to centimeters",
  "  ",
  "  // Display the distance on the LCD",
  "  lcd.setCursor(0, 1); // Move to second line",
  "  lcd.print(\"Distance: \");",
  "  lcd.print(cm);",
  "  lcd.print(\" cm   \"); // Extra spaces to clear previous text",
  "",
  "  // Delay before the next measurement",
  "  delay(500);",
  "}"
]